git.exe config --global alias.cm '!git checkout master && git merge --ff-only' 
git.exe config --global alias.last 'log -1 HEAD'
git.exe config --global alias.lol 'log --oneline --decorate --graph'
git.exe config --global alias.pristine '!git reset --hard && git clean -dffx'
git.exe config --global alias.rf 'checkout HEAD^1 --'
git.exe config --global alias.stage 'add'
git.exe config --global alias.unstage 'reset HEAD --'
git.exe config --global alias.visual '!C:/Users/maxim/AppData/Local/Fork/Fork.exe'
git.exe config --global alias.istage '!git-istage'